### ISSUE TITLE
Example signature could be more clear

### ISSUE THREAD

**Issue by girifox** [skypyxis/OutlookCO2#1]
Hi mate, this is a great idea.
Your example signature has this 
`1 | 10 years ago: 405.62 | 384.73 ppm`

I think it would be more clear if instead it was:
`10 years ago: 384.73 ppm`

**Comment by skypyxis** [comment]
Thanks for the feedback!  

It was updated to:
```
Today's CO2 atmospheric concentration: {CO2-D} ppm  
1 year ago: {CO2-D-1Y} ppm | 10 years ago: {CO2-W-10Y} ppm
```
